from .AlkanSubstituent import alkan_substituent
from .AlkoholSubstituent import alkohol_substituent
from .AminoSubstituent import amino_substituent
from .HalogenSubstituent import halogen_substituent
from .PhenylSubstituent import phenyl_substituent
from .KetonSubstituent import keton_substituent
from .SaeureSubstituent import saeure_substituent
from .AldehydSubstituent import aldehyd_substituent
